// @ts-check

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

module.exports = {
  // Cambria Stream Sidebar
  StreamSidebar: [
    {
      type: 'category',
      label: 'Installation Guides',
      items: [
        {
          type: 'category',
          label: 'Kubernetes',
          items: [
            {
              type: 'category',
              label: 'AWS',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Cambria Stream/01-Installation Guides/01-Kubernetes/01-AWS',
                },
              ],
            },
            {
              type: 'category',
              label: 'Akamai',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Cambria Stream/01-Installation Guides/01-Kubernetes/02-Akamai',
                },
              ],
            },
            {
              type: 'category',
              label: 'Oracle',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Cambria Stream/01-Installation Guides/01-Kubernetes/03-Oracle',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Windows',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Cambria Stream/01-Installation Guides/02-Windows',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cambria Stream/02-Release Notes',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        'Cambria Stream/API/Introduction',
        'Cambria Stream/API/Event_Description',
        {
          type: 'category',
          label: 'API Methods',
          link: {
            type: 'doc',
            id: 'Cambria Stream/API/API_Methods',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'Cambria Stream/03-API/API_Methods',
            },
          ],
        },
        {
          type: 'category',
          label: 'Event Attributes',
          link: {
            type: 'doc',
            id: 'Cambria Stream/API/Event_Attributes',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'Cambria Stream/03-API/Event_Attributes',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cambria Stream/04-Tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cambria Stream/05-FAQ',
        },
      ],
    },
  ],

  // Cambria FTC Sidebar
  FTCSidebar: [
    {
      type: 'category',
      label: 'Installation Guides',
      items: [
        {
          type: 'category',
          label: 'Kubernetes',
          items: [
            {
              type: 'category',
              label: 'AWS',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Cambria_FTC/01-Installation Guides/01-Kubernetes/01-AWS',
                },
              ],
            },
            {
              type: 'category',
              label: 'Akamai',
              items: [
                {
                  type: 'doc',
                  id: 'Cambria_FTC/Installation Guides/Kubernetes/Akamai/Akamai-Kubernetes/Cambria_Cluster_Akamai_Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'Cambria_FTC/Installation Guides/Kubernetes/Akamai/Akamai-Kubernetes/cambria-cluster-ftc-5-6-akamai-kubernetes',
                  label: 'Cambria Cluster Akamai Kubernetes',
                },
              ],
            },
            {
              type: 'category',
              label: 'Oracle',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Cambria_FTC/01-Installation Guides/01-Kubernetes/03-Oracle',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Windows',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Cambria_FTC/01-Installation Guides/02-Windows',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cambria_FTC/02-Release Notes',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cambria_FTC/03-API',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cambria_FTC/04-Tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Cambria_FTC/05-FAQ',
        },
      ],
    },
  ],
};
