// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Cambria Stream Sidebar
  StreamSidebar: [
    {
      type: 'category',
      label: 'Installation Guides',
      link: {
        type: 'generated-index',
        slug: '/cambria-stream/installation-guides',
        description: 'Installation Guides for Cambria Stream',
      },
      items: [
        {
          type: 'category',
          label: 'Kubernetes',
          link: {
            type: 'generated-index',
            slug: '/cambria-stream/installation-guides/kubernetes',
            description: 'Kubernetes Installation Guides for Cambria Stream',
          },
          items: [
            {
              type: 'category',
              label: 'AWS',
              link: {
                type: 'generated-index',
                slug: '/cambria-stream/installation-guides/kubernetes/aws',
                description: 'AWS Installation Guides for Cambria Stream',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cambria-stream/installation-guides/kubernetes/aws',
                },
              ],
            },
            {
              type: 'category',
              label: 'Akamai',
              link: {
                type: 'generated-index',
                slug: '/cambria-stream/installation-guides/kubernetes/akamai',
                description: 'Akamai Installation Guides for Cambria Stream',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cambria-stream/installation-guides/kubernetes/akamai',
                },
              ],
            },
            {
              type: 'category',
              label: 'Oracle',
              link: {
                type: 'generated-index',
                slug: '/cambria-stream/installation-guides/kubernetes/oracle',
                description: 'Oracle Installation Guides for Cambria Stream',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cambria-stream/installation-guides/kubernetes/oracle',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Windows',
          link: {
            type: 'generated-index',
            slug: '/cambria-stream/installation-guides/windows',
            description: 'Windows Installation Guides for Cambria Stream',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cambria-stream/installation-guides/windows',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      link: {
        type: 'generated-index',
        slug: '/cambria-stream/release-notes',
        description: 'Release Notes for Cambria Stream',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cambria-stream/release-notes',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'generated-index',
        slug: '/cambria-stream/api',
        description: 'API for Cambria Stream',
      },
      items: [
        'cambria-stream/api/introduction',
        'cambria-stream/api/event-descriptions',
        {
          type: 'category',
          label: 'API Methods',
          link: {
            type: 'doc',
            id: 'cambria-stream/api/api-methods',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cambria-stream/api/api-methods',
            },
          ],
        },
        {
          type: 'category',
          label: 'Event Attributes',
          link: {
            type: 'doc',
            id: 'cambria-stream/api/event-attributes',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cambria-stream/api/event-attributes',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        slug: '/cambria-stream/tutorials',
        description: 'Tutorials for Cambria Stream',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cambria-stream/tutorials',
        },
      ],
    },
    {
      type: 'doc',
      label: 'FAQs',
      id: 'cambria-stream/customer-faqs',
    },
  ],

  // Cambria FTC Sidebar
  FTCSidebar: [
    {
      type: 'category',
      label: 'FTC Overview',
      link: {
        type: 'generated-index',
        slug: '/cambria-ftc/ftc-overview',
        description: 'Overview of Cambria FTC',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cambria-ftc/ftc-overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Installation Guides',
      link: {
        type: 'generated-index',
        slug: '/cambria-ftc/installation-guides',
        description: 'Installation Guides for Cambria FTC',
      },
      items: [
        {
          type: 'category',
          label: 'Kubernetes',
          link: {
            type: 'generated-index',
            slug: '/cambria-ftc/installation-guides/kubernetes',
            description: 'Kubernetes Installation Guides for Cambria FTC',
          },
          items: [
            {
              type: 'category',
              label: 'AWS',
              link: {
                type: 'generated-index',
                slug: '/cambria-ftc/installation-guides/kubernetes/aws',
                description: 'AWS Kubernetes Installation for Cambria FTC',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cambria-ftc/installation-guides/kubernetes/aws',
                },
              ],
            },
            {
              type: 'category',
              label: 'Akamai',
              link: {
                type: 'generated-index',
                slug: '/cambria-ftc/installation-guides/kubernetes/akamai',
                description: 'Akamai Kubernetes Installation for Cambria FTC',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cambria-ftc/installation-guides/kubernetes/akamai',
                },
              ],
            },
            {
              type: 'category',
              label: 'Oracle',
              link: {
                type: 'generated-index',
                slug: '/cambria-ftc/installation-guides/kubernetes/oracle',
                description: 'Oracle Kubernetes Installation for Cambria FTC',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cambria-ftc/installation-guides/kubernetes/oracle',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Windows',
          link: {
            type: 'generated-index',
            slug: '/cambria-ftc/installation-guides/windows',
            description: 'Windows Installation Guides for Cambria FTC',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cambria-ftc/installation-guides/windows',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      link: {
        type: 'generated-index',
        slug: '/cambria-ftc/release-notes',
        description: 'Release Notes for Cambria FTC',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cambria-ftc/release-notes',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'generated-index',
        slug: '/cambria-ftc/api',
        description: 'API for Cambria FTC',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cambria-ftc/api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        slug: '/cambria-ftc/tutorials',
        description: 'Tutorials for Cambria FTC',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cambria-ftc/tutorials',
        },
      ],
    },
    {
      type: 'doc',
      label: 'FAQs',
      id: 'cambria-ftc/customer-faqs',
    },
  ],
};

export default sidebars;